[package]
name = "paddle-rust-sdk-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum = { workspace = true, optional = true }
